<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
<xsl:param name="delimiter" select=" '|' "/>
	<xsl:output method="text" version="1.0" encoding="UTF-8" indent="no"/>

	<xsl:template match="/">
	<xsl:text>Base|A260280 Ratio|Able to Initiate on DNA with 3 ext|Able to Initiate on DNA with 5 ext|Able to Initiate on DNA with Blunt|Able to Initiate on DNA with Nick|Activity In NEBuffers|Activity in Activity without 5 phosphate|Affinity Tag|Anomericity|Antibody Type|Assay Substrate|Binding Capacity|Blue White Screening|Buffer Component Hide|Buffer pH|Buffer Temperature|Can be Regenerated|Can Be Used for Blue White Section|Cloning Sub Cloning|Competent Cell Application|Competent Cell Type|Composite Product Type|Control Plasmid Included|Copy Number|Cuts Bi Antennary|Cuts High Manosse|Cuts Hybrid|Cuts In Core|Cuts Tetra Antennary|Cuts Tri Antennary|Cytoplasmic disulfide bond formation|DAM|DCM|Deactivation|Detection Method|Dilution for Comet Assay|Drug Resistance|dsDNA Substrate|dsRNA Substrate|EcoKM|EcoKR|Emission Color|Emission Name|End Labeled FAM Cleavage|End Product|Endo I Deficient|Engineered|Epitope|Excitation|Expr 1|Expr 2|Expr 3|Extraction Free|F aka SS phage|Format|four hrs digestion completed|four hrs min after preincubation|Free of Animal Products|Gel Type|Gen Bank Assession Number|General Utility|Genotype|Glycosidase Recognition Site Alt Text|Glycosidase Recognition Site Caption|Glycosidase Recognition Site GUID|Glycosidase Recognition Site Name|Glycosidase Recognition Site URL|Growth Media|Growth Medium and Conditions|Growth Temperature|Hardware Pressure Limit|Hardware Pressure Limit UOM|Icon|Introduction|Is NEB Product|Iso Type|Joining of RNA in a DS Structure|Joining SS and DS RNA Oligos|Kunkel Mutagenesis|Lac Repressoron Plasmid|lacl|laclq|Library Construction|Library Preparation|Ligation And Recutting|Long Amp Taqin Long Amp Taq Buffer|Lot Control|Lysy|Marker Sample Type|Marker Size|Master Mix Available|Max Adjustment|Max Units Without Star Activity|McrA|McrB|Melting Method|Melting Temperature|Method Of Cleavage|Method Overview|Methylase Type|Min Adjustment|NEBNext Selection Tool|Nuclease Type|One Taqin One Taq Buffer|Orientation|Over Hang Description|Over Hang Length|Over Hang Sequence|Partial Digestion of ss Extension|Peptide Sequence|Phosphorothioate Cleavage|Phusion in Phusion HF Buffer|Plasmid Map|Plasmid Size|Polarity|Polylinker|Polylinker DNA Sequence|Position on Complement|Position on Sequence|Preparation|Price Advantage|Primer Sequence|Product Source|Promoters|Protease Cleavage Site|Protease Deficient|Protease Type|Protection Assay Conditions|Protocol Times|Purification Method|Purity|Q5 in Q5 Buffer|Quantitation|Reaction Buffer|Reaction Buffer Usage Concentration Factor|Reaction Buffer Usage Concentration Factor Max|Reaction Buffer Usage Concentration Factor Min|Reaction Conditions|RecA|Recommended Buffers|Recommended Cloning|Recommended Dilution for Western Blot|Recommended Load Mass Max|Recommended Load Mass Min|Recommended Load Volume Max|Recommended Load Volume Min|Recommended Resuspension UOM|Recommended Resuspension Value|Recommended Working Dilution|Removal|Restriction Sites Not Present|Sample Enrichment|Selection Markers|Sensitivity|Sensitivity UOM|Sequence|Sequencing Platform|sixteen hrs digestion completed|sixteen hrs min after preincubation|SOC Included|Sold as Linear|Sold As Single Stranded|Solutions and Recipes|Source|Source Species|Specific Activity|Specific Activity PNPP Value|Specific Activity PNPP Value Uom|Specific Activity PSP Value|Specific Activity PSP Value UOM|Specific Activity PTP Value|Specific Activity PTP Value UOM|Specific Activity UOM|Specificity|Specificity Cross Reactivity|ssDNA Substrate|ssRNA Substrate|Storage Condition Hide|Storage Condition pH|Storage Condition Temperature|Strain|Strain Type|Suggested Working Concentration Max|Suggested Working Concentration Min|Suggested Working Concentration UOM|Suitability for extended digests|Supplement Requirements|Support Matrix|T1 Phase Resistant|T7 RNA Polymerase|Taq in Standard Taq Reaction Buffer|Taq in Thermo Pol Reaction Buffer|Target Antigen|Terminal Monosacarides|Transformation Efficiency|two hrs digestion completed|two hrs min after preincubation|Type|Typical Recovery|Unit Assay Conditions|Unit Definition|Units For 90 Pct Digestion Of 2 MicroMoleOligos|Units for Complete Digestion Four Hrs|Units for Complete Digestion sixteen Hrs|Units for Complete Digestion Two Hrs|Units Per 50 Micro Liter Reaction|Units Required for 100 Pct Phosphate Removal Max|Units Required for 100 Pct Phosphate Removal Min|Units to Cleave Lambda|Units to Cleave Plasmid|Vector Set|Phosphorylation Site|Polylinker Region Start|Polylinker Region Stop|Polylinker Sequence|Products Produced|Protein Substrate|Recognition Determinant|Recognition Motif|Recommended Cloning Site|Self Complementary|Tag|Unit Assay Buffer Is NEB Product|Unit Assay Buffer Note|Sequence Length Min|Sequence Length Max|Sequence Length UOM|Is Phosphorylated|Usage Concentration Min|Usage Concentration Max|Usage Concentration UOM
</xsl:text>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/CoreProductInfo/CatalogNumber)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/A260280Ratio)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AbletoInitiateonDNAwith3ext)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AbletoInitiateonDNAwith5ext)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AbletoInitiateonDNAwithBlunt)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AbletoInitiateonDNAwithNick)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ActivityInNEBuffers)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Activitywithout5phosphate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AffinityTag)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Anomericity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/AntibodyType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/AssaySubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/BindingCapacity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/BlueWhiteScreening)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/BufferComponents/BufferComponentHide)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/BufferComponents/BufferpH)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/BufferComponents/BufferTemperature)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CanbeRegenerated)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CanBeUsedforBlueWhiteSection)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CloningSubCloning)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CompetentCellApplication)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CompetentCellType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CompositeProductType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ControlPlasmidIncluded)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CopyNumber)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsBiAntennary)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsHighManosse)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsHybrid)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsInCore)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsTetraAntennary)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/CutsTriAntennary)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Cytoplasmicdisulfidebondformation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/DAM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/DCM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Deactivation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/DetectionMethod)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/DilutionforCometAssay)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/DrugResistance)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/dsDNASubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/dsRNASubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/EcoKM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/EcoKR)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Emission/Emissions/EmissionColor)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Emission/Emissions/EmissionName)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/EndLabeledFAMcleavage)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/EndProduct)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/EndoIDeficient)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Engineered)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Epitope)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Excitation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Expr1)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Expr2)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Expr3)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ExtractionFree)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/FakaSSphage)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Format)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/fourhrsdigestioncompleted)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/fourhrsminafterpreincubation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/FreeofAnimalProducts)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GelType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GenBankAssessionNumber)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GeneralUtility)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Genotype)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/GlycosidaseRecognitionSite/GlycosidaseRecognitionSiteAltText)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/GlycosidaseRecognitionSite/GlycosidaseRecognitionSiteCaption)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/GlycosidaseRecognitionSite/GlycosidaseRecognitionSiteGuid)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/GlycosidaseRecognitionSite/GlycosidaseRecognitionSiteName)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/GlycosidaseRecognitionSite/GlycosidaseRecognitionSiteUrl)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GrowthMedia)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GrowthMediumandConditions)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/GrowthTemperature)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Hardwarepressurelimit/HardwarePressureLimit/Hardwarepressurelimit)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Hardwarepressurelimit/HardwarePressureLimit/HardwarePressureLimitUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Icon)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Introduction)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/IsNEBProduct)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Isotype)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/JoiningofRNAinaDSStructure)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/JoiningSSandDSRNAOligos)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/KunkelMutagenesis)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LacRepressoronPlasmid)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/lacl)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/laclq)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LibraryConstruction)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LibraryPreparation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LigationAndRecutting)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LongAmpTaqinLongAmpTaqBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/LotControl)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Lysy)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MarkerSampleType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MarkerSize)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MasterMixAvailable)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MaxAdjustment)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MaxUnitsWithoutStarActivity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/McrA)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/McrB)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MeltingMethod)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MeltingTemperature)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MethodOfCleavage)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MethodOverview)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MethylaseType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/MinAdjustment)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/NEBNextSelectionTool)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/NucleaseType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/OneTaqinOneTaqBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Orientation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/OverHangDescription)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/OverHangLength)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/OverHangSequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PartialDigestionofssExtension)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PeptideSequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PhosphorothioateCleavage)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PhusioninPhusionHFBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PlasmidMap)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PlasmidSize)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Polarity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Polylinker)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PolylinkerDNASequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PositiononComplement)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PositiononSequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Preparation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PriceAdvantage)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PrimerSequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProductSource)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Promoters)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProteaseCleavageSite)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProteaseDeficient)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProteaseType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProtectionAssayConditions)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProtocolTimes)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PurificationMethod)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Purity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Q5inQ5Buffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Quantitation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/ReactionBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/ReactionBufferUsageConcentrationFactor/ReactionBufferUsageconcentrationfactor)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/ReactionBufferUsageConcentrationFactor/ReactionBufferUsageConcentrationFactorMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/ReactionBufferUsageConcentrationFactor/ReactionBufferUsageConcentrationFactorMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ReactionConditions)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecA)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedBuffers)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedCloning)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedDilutionforWesternBlot)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedLoadMassMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedLoadMassMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedLoadVolumeMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedLoadVolumeMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedResuspensionUOM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedResuspensionValue)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedWorkingDilution)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Removal)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RestrictionSitesNotPresent)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SampleEnrichment)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SelectionMarkers)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Sensitivity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SensitivityUOM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Sequence)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SequencingPlatform)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/sixteenhrsdigestioncompleted)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/sixteenhrsminafterpreincubation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SOCIncluded)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SoldasLinear)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SoldasSingleStranded)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SolutionsandRecipes)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Source)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SourceSpecies)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivitys/SpecificActivity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPNPPValues/SpecificActivityPNPPValue)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPNPPValues/SpecificActivityPNPPValueUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPSPValues/SpecificActivityPSPValue)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPSPValues/SpecificActivityPSPValueUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPTPValues/SpecificActivityPTPValue)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivityPTPValues/SpecificActivityPTPValueUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SpecificActivitys/SpecificActivityUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Specificity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SpecificityCrossReactivity)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ssDNASubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ssRNASubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/StorageConditions/StorageConditionHide)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/StorageConditions/StorageConditionpH)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/StorageConditions/StorageConditionTemperature)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Strain)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/StrainType)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SuggestedWorkingConcentrationMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SuggestedWorkingConcentrationMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SuggestedWorkingConcentrationUOM)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Suitabilityforextendeddigests)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SupplementRequirements)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SupportMatrix)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/T1Phaseresistant)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/T7RNAPolymerase)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TaqinstdTaqReactionBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TaqinThermoPolReactionBuffer)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TargetAntigen)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TerminalMonosacarides)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TransformationEfficiency)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/twohrsdigestioncompleted)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/twohrsminafterpreincubation)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Type)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/TypicalRecovery)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitAssayConditions)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitDefinition)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitsFor90PercentDigestionOf2MicroMoleOligos)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitsforCompleteDigestionFourHrs)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitsforCompleteDigestionsixteenHrs)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/UnitsforCompleteDigestion/UnitsforCompleteDigestionTwoHrs)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitsPer50MicroLiterReaction)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/UnitsRequiredfor100percentPhosphateRemoval/UnitsRequiredfor100percentPhosphateRemovalMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/UnitsRequiredfor100percentPhosphateRemoval/UnitsRequiredfor100percentPhosphateRemovalMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitstoCleaveLambda)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/UnitstoCleavePlasmid)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/VectorSet)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/PhosphorylationSite)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/PolylinkerRegion/PolylinkerRegionstart)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/PolylinkerRegion/PolylinkerRegionstop)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/PolylinkerSequence)"/> <xsl:value-of select="$delimiter"/>
		<xsl:for-each select="/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/Productsproduced/ProductItem">
			<xsl:value-of select="normalize-space(Product)"/>
			<xsl:if test="position()!=last()">
				<xsl:text>, </xsl:text>
			</xsl:if>
			<xsl:if test="position()=last()-1">
				<xsl:text> </xsl:text>
			</xsl:if>
		</xsl:for-each>
		<xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/ProteinSubstrate)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecognitionDeterminant)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecognitionMotif)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/RecommendedCloningSite)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/SelfComplementary)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/Tag)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/UnitAssayBuffer/IsNEBProduct)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/UnitAssayBuffer/Note)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SequenceLength/SequenceLengthMin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SequenceLength/SequenceLengthMax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/ClassSpecific/SequenceLength/SequenceLengthUom)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(ClassSpecific/IsPhosphorylated)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/Usage/UsageConcentrationmin)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/Usage/UsageConcentrationmax)"/> <xsl:value-of select="$delimiter"/>
<xsl:value-of select="normalize-space(/ProductDetailsBySku/ProductDetailsBySku/Usage/UsageConcentrationUom)"/> 

</xsl:template>
</xsl:stylesheet>